import React, {useRef, useState, useEffect} from 'react';
import * as tfjs from '@tensorflow/tfjs';
import * as handpose from '@tensorflow-models/handpose';
import Webcam from 'react-webcam';
import * as fingerpose from 'fingerpose';
import Handsigns from '../handsigns';
import {Text, Heading, Button, Image, Stack, Container, Box, VStack, ChakraProvider} from '@chakra-ui/react';
import './app.css';
import '@tensorflow/tfjs-backend-webgl';
import {RiCameraFill, RiCameraOffFill} from "react-icons/ri";